import { Map } from 'immutable';
import { SimpleNamespace } from './Namespace';
export declare const INTERNAL_PREFIX = "__internal_";
export declare const SUBJECT_BINDING_BASE = "_subject";
export declare const SUBJECT_BINDING: string;
export declare const PARENT_BINDING_BASE = "_parent";
export declare const PARENT_BINDING: string;
export declare const TYPENAME_BINDING_BASE = "_typename";
export declare const TYPENAME_BINDING: string;
export declare const ID_BINDING_BASE = "_id";
export declare const ID_KEY = "id";
export declare const ID_BINDING: string;
export declare const INTERNAL_ID_KEY: string;
export declare const DEFAULT_GEO_BINDING = "schema_location";
export declare const RDFS_LABEL_KEY = "rdfs_label";
export declare const INTERNAL_RDFS_LABEL_BINDING: string;
export declare const DEFAULT_PREFIXES: Map<string, SimpleNamespace>;
