import {GQLObjectQueryModifierPrimitiveExpression} from './GQLObjectQueryModifierPrimitiveExpression';

export class GQLObjectQueryModifierBasicPrimitiveExpression extends GQLObjectQueryModifierPrimitiveExpression {
}
